/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import Business.Ecosystem;
import Customer.Customer;
import HomePainting.HomePainting;
import HomePainting.PaintingPackages;
import UserAccounts.UserAccounts;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hi
 */
public class PaintingCartJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaintingCartJPanel
     */
    
    private JPanel workAreaContainer;
    private Ecosystem ecosystem;
    private UserAccounts userAccount;
    HomePainting painting;
    ArrayList<PaintingPackages> servicesOff = new ArrayList<PaintingPackages>();
    
    public PaintingCartJPanel(JPanel workAreaContainer, UserAccounts userAccount, Ecosystem ecosystem, HomePainting painting) {
        initComponents();
        
        this.workAreaContainer = workAreaContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        this.painting = painting;
        populatePaintTable();
    }

    public PaintingCartJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        addCartBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        removeBtn = new javax.swing.JButton();
        placebtn = new javax.swing.JButton();
        fieldComments = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        addCartBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addCartBtn.setText("Add to Cart");
        addCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCartBtnActionPerformed(evt);
            }
        });
        add(addCartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paint Name", "Paint Description", "Paint Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(serviceTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 95));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("YOUR PAINTING SERVICES CART");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Comments:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, -1, -1));
        add(fieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 178, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Service Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("YOUR CART");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, -1));

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paint Name", "Paint Description", "Paint Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(cartTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 426, 91));

        removeBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        removeBtn.setText("Remove from Cart");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, -1, -1));

        placebtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        placebtn.setText("Place Request");
        placebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placebtnActionPerformed(evt);
            }
        });
        add(placebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, -1, -1));
        add(fieldComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 178, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Customer/painiting1.jpeg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -220, 1750, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void populatePaintTable() {
        DefaultTableModel model = (DefaultTableModel) serviceTable.getModel();
        model.setRowCount(0);
            Object[] row = new Object[3];
            for(PaintingPackages req:painting.getPaintingPackageList()){
                 row[0] = req;
                 row[1] = req.getPaintDesc();
                 row[2] = req.getColor();
                 model.addRow(row);
            }  
    }
     private void populateCartTable(PaintingPackages paint) {
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        model.setRowCount(0);

        servicesOff.add(paint);
        
        Object[] row = new Object[3];
        for(PaintingPackages req:servicesOff){
            row[0] = req;
            row[1] = req.getPaintDesc();
            row[2] = req.getColor();
            
            model.addRow(row);
        }  
    }

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCartBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = serviceTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "No Selections Made", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            PaintingPackages paint = (PaintingPackages)serviceTable.getValueAt(selectedRow, 0);
            populateCartTable(paint);
        }

    }//GEN-LAST:event_addCartBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = cartTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "No Selections Made", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            PaintingPackages paint = (PaintingPackages)cartTable.getValueAt(selectedRow, 0);
            servicesOff.remove(paint);
            DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
            model.setRowCount(0);
            Object[] row = new Object[3];
            for(PaintingPackages req:servicesOff){
                row[0] = req;
                row[1] = req.getPaintDesc();
                row[2] = req.getColor();
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void placebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placebtnActionPerformed
        // TODO add your handling code here:
        String address = fieldAddress.getText();
        String comments = fieldComments.getText();

        try {
            if(address==null || address.isEmpty()){
                throw new NullPointerException("Please Enter Service Address !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please Enter Service Address !!!");
            return;
        }

        painting.newPaintingRequest(painting.getPaintName(), userAccount.getUsername(), null, servicesOff , address, comments);
        for(Customer cust:ecosystem.getCustomerDirectory().getCustomerList()){
            if(userAccount.getUsername().equals(cust.getUsername())){
                cust.createPaintingServiceRequest(painting.getPaintName(), userAccount.getUsername(), null, servicesOff , address, comments);
            }
        }

        JOptionPane.showMessageDialog(null,"Your Request is placed Successfully !!!", "Thank You", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_placebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCartBtn;
    private javax.swing.JTable cartTable;
    private javax.swing.JTextField fieldAddress;
    private javax.swing.JTextField fieldComments;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton placebtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JTable serviceTable;
    // End of variables declaration//GEN-END:variables
}
