/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import Business.Ecosystem;
import Customer.Customer;
import PestControlOrganization.PestControl;
import UserAccounts.UserAccounts;
import WorkQueue.PestControlWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hi
 */
public class PestControlCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PestControlCustomerJPanel
     */
    private JPanel workAreaContainer;
    private Ecosystem ecosystem;
    private UserAccounts userAccount;

    
     public PestControlCustomerJPanel(JPanel workAreaContainer, UserAccounts userAccount, Ecosystem ecosystem) {
        initComponents();
        
        this.workAreaContainer = workAreaContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        populateServiceTable();
        populateRequestTable();
       
    }
    public PestControlCustomerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orgTable = new javax.swing.JTable();
        cartBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("PEST CONTROL SERVICE DASHBOARD");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 6, 510, -1));

        orgTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organisation Name", "Organisation Address", "Organisation Contact", "Organisation Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orgTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 135, 542, 155));

        cartBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cartBtn.setText("View Services Offered");
        cartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartBtnActionPerformed(evt);
            }
        });
        add(cartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 308, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel2.setText("Pick A Painting Organisation of your choice:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 101, 487, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel3.setText("Your Service Requests:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 411, 216, -1));

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Organisation Name", "Address", "Request Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 451, 538, 155));

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 390, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Customer/pests22.jpeg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -100, 1490, 1140));
    }// </editor-fold>//GEN-END:initComponents

    private void populateServiceTable() {
        
        DefaultTableModel paintTableModel = (DefaultTableModel) orgTable.getModel();
        paintTableModel.setRowCount(0);
        
            Object[] row = new Object[4];    
            for(PestControl pest:ecosystem.getPestControlDirectory().getPestControlOrgList()){
                 row[0] = pest;
                 row[1] = pest.getPestControlOrgAddress();
                 row[2] = pest.getPestControlOrgPhNum();
                 row[3] = pest.getPestControlOrgEmail();
                 
                 paintTableModel.addRow(row);
            }
            
    }

    public void populateRequestTable() {
        
        DefaultTableModel requestTableModel = (DefaultTableModel) requestTable.getModel();
        requestTableModel.setRowCount(0);

          ArrayList<Customer> customerlist = ecosystem.getCustomerDirectory().getCustomerList();
        if(customerlist!=null){
          for (Customer cust:customerlist) {   
            if (cust.getUsername().equals(userAccount.getUsername())) {
               for(PestControlWorkRequest pest:cust.getPestControlWorkRequestList()){
                Object[] row = new Object[4];
                row[0] = pest;
                row[1] = pest.getPestControlCOmpanyName();
                row[2] = pest.getServiceAddress();
                row[3] = pest.getStatus();
                requestTableModel.addRow(row);
               }            
            }  
          
    }
        }}
    
    private void cartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = orgTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"No Selections Made!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            PestControl home = (PestControl)orgTable.getValueAt(selectedRow, 0);
            PestControlCartJPanel cart = new PestControlCartJPanel(workAreaContainer, userAccount, ecosystem, home);
            workAreaContainer.add("Pest Control Cart", cart);
            CardLayout layout=(CardLayout)workAreaContainer.getLayout();
            layout.next(workAreaContainer);
        }
    }//GEN-LAST:event_cartBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        populateRequestTable();
    }//GEN-LAST:event_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cartBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orgTable;
    private javax.swing.JButton refresh;
    private javax.swing.JTable requestTable;
    // End of variables declaration//GEN-END:variables
}
