/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import Business.Ecosystem;
import Customer.Customer;
import PestControlOrganization.PestControl;
import PestControlOrganization.PestControlServices;
import UserAccounts.UserAccounts;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hi
 */
public class PestControlCartJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PestControlCartJPanel
     */
    
    private JPanel workAreaContainer;
    private Ecosystem ecosystem;
    private UserAccounts userAccount;
    PestControl pestControl;
    ArrayList<PestControlServices> servicesOff = new ArrayList<PestControlServices>();
    
    public PestControlCartJPanel() {
        initComponents();
    }
    
    public PestControlCartJPanel(JPanel workAreaContainer, UserAccounts userAccount, Ecosystem ecosystem, PestControl pestControl) {
        initComponents();
        
        this.workAreaContainer = workAreaContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        this.pestControl = pestControl;
        
       
        populateService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        addCartBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        placebtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldComments = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 32, -1, -1));

        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Service Name", "Service Description", "Service Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(serviceTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 119, -1, 95));

        addCartBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addCartBtn.setText("Add to Cart");
        addCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCartBtnActionPerformed(evt);
            }
        });
        add(addCartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 232, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("YOUR PEST CONTROL SERVICES CART");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 14, -1, -1));

        placebtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        placebtn.setText("Place Request");
        placebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placebtnActionPerformed(evt);
            }
        });
        add(placebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 677, -1, -1));

        removeBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        removeBtn.setText("Remove from Cart");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 677, -1, -1));

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Service Type", "Service Description", "Service Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(cartTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 434, 426, 91));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("YOUR CART");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 399, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Service Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, -1, -1));
        add(fieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 553, 178, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Comments:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 615, -1, -1));
        add(fieldComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 610, 178, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Customer/cartoon-pest-control-service-business-vector-17191623.jpeg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-42, -87, 1750, 1200));
    }// </editor-fold>//GEN-END:initComponents

    private void populateCart(PestControlServices pest) {
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        model.setRowCount(0);

        servicesOff.add(pest);
        
        Object[] row = new Object[3];
        for(PestControlServices p:servicesOff){
            row[0] = p;
            row[1] = p.getServiceDescription();
            row[2] = p.getServiceType();
            
            model.addRow(row);
        }  
    }
    
    private void populateService() {
        DefaultTableModel model = (DefaultTableModel) serviceTable.getModel();
        model.setRowCount(0);
            Object[] row = new Object[3];
            for(PestControlServices req:pestControl.getPestControlServiceList()){
                 row[0] = req;
                 row[1] = req.getServiceDescription();
                 row[2] = req.getServiceType();
                 model.addRow(row);
            }  
    }
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCartBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = serviceTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "No Selections Made", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            PestControlServices serv = (PestControlServices)serviceTable.getValueAt(selectedRow, 0);
            populateCart(serv);
        }
    }//GEN-LAST:event_addCartBtnActionPerformed

    private void placebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placebtnActionPerformed
        // TODO add your handling code here:
        String address = fieldAddress.getText();
        String comments = fieldComments.getText();

        try {
            if(address==null || address.isEmpty()){
                throw new NullPointerException("Please Enter Service Address !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please Enter Service Address !!!");
            return;
        }

        pestControl.newPestControlRequest(pestControl.getPestControlOrgName(), userAccount.getUsername(), null, servicesOff , address, comments);
        for(Customer cust:ecosystem.getCustomerDirectory().getCustomerList()){
            if(userAccount.getUsername().equals(cust.getUsername())){
                cust.createPestControlRequest(pestControl.getPestControlOrgName(), userAccount.getUsername(), null, servicesOff , address, comments);
            }
        }

        JOptionPane.showMessageDialog(null,"Your Request is placed Successfully !!!", "Thank You", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_placebtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = cartTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "No Selections Made", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            PestControlServices pest = (PestControlServices)cartTable.getValueAt(selectedRow, 0);
            servicesOff.remove(pest);
            DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
            model.setRowCount(0);
            Object[] row = new Object[3];
            for(PestControlServices req:servicesOff){
                row[0] = req;
                row[1] = req.getServiceDescription();
                row[2] = req.getServiceType();
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_removeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCartBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable cartTable;
    private javax.swing.JTextField fieldAddress;
    private javax.swing.JTextField fieldComments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton placebtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JTable serviceTable;
    // End of variables declaration//GEN-END:variables
}
