/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.StoreAdmin;

import Business.Ecosystem;
import UserAccounts.UserAccounts;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author hi
 */
public class MetricsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MetricsJPanel
     */
    
    private JPanel workAreaContainer;
    private Ecosystem ecosystem;
    private UserAccounts userAccount;

    public MetricsJPanel(JPanel workAreaContainer, UserAccounts userAccount, Ecosystem ecosystem) {
        initComponents();
        
        this.workAreaContainer = workAreaContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        
    }
    
    public MetricsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pie = new javax.swing.JButton();
        bar = new javax.swing.JButton();
        line = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pie.setText("Pie Chart");
        pie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieActionPerformed(evt);
            }
        });
        add(pie, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        bar.setText("Bar Graph");
        bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barActionPerformed(evt);
            }
        });
        add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        line.setText("Line Chart");
        line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineActionPerformed(evt);
            }
        });
        add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset = new  DefaultCategoryDataset();
        dataset.setValue( 5, "Values", "Products Crated");
        dataset.setValue( 2, "Values", "Buyers");

        
        JFreeChart chart = ChartFactory.createBarChart("Parameter Values","Parameters","Values", dataset, PlotOrientation.VERTICAL, false, true, false);
        chart.setBackgroundPaint(Color.YELLOW);
        chart.getTitle().setPaint(Color.RED);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLUE);
        ChartFrame frame=new ChartFrame("Bar Chart for Parameters",chart);
        frame.setVisible(true);
        frame.setSize(450,350);


    }//GEN-LAST:event_barActionPerformed

    private void pieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieActionPerformed
        // TODO add your handling code here:pieDataset.setValue("Products Created", 5);
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Products Created", 5);
        pieDataset.setValue("Buyers", 2);
        
        JFreeChart piechart = ChartFactory.createPieChart("Pie Chart", pieDataset, true, true, true);
        PiePlot piechrt = (PiePlot)piechart.getPlot();
        //piechrt.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame chrtframe = new ChartFrame("Pie Chart", piechart);
        chrtframe.setVisible(true);
        chrtframe.setSize(1200,850);
        chrtframe.setBackground(Color.WHITE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        chrtframe.setLocation(dim.width/2-this.getSize().width/2, dim.height/2- this.getSize().height/2);
    }//GEN-LAST:event_pieActionPerformed

    private void lineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineActionPerformed
        // TODO add your handling code here:
         DefaultCategoryDataset dataset = new  DefaultCategoryDataset();
        dataset.setValue( 5, "Values", "Products Crated");
        dataset.setValue( 2, "Values", "Buyers");

        JFreeChart chart = ChartFactory.createLineChart("Parameter Values","Parameters","Values", dataset, PlotOrientation.VERTICAL, false, true, false);
        chart.setBackgroundPaint(Color.YELLOW);
        chart.getTitle().setPaint(Color.RED);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLUE);
        ChartFrame frame=new ChartFrame("Line Chart for Parameters",chart);
        frame.setVisible(true);
        frame.setSize(450,350);
    }//GEN-LAST:event_lineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton line;
    private javax.swing.JButton pie;
    // End of variables declaration//GEN-END:variables
}
