/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PestControlAdmin;

import Beautician.BeauticianWorker;
import Business.Ecosystem;
import Customer.Customer;
import PestControlTechnician.PestControlTechnician;
import UserAccounts.UserAccounts;
import WorkQueue.HomePaintingWorkRequest;
import WorkQueue.PestControlWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 91730
 */
public class AssignTechnicianJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignTechnicianJPanel
     */
    private JPanel workAreaContainer;
    private Ecosystem ecosystem;
    private UserAccounts userAccount;
    private PestControlWorkRequest request;
    
    
    public AssignTechnicianJPanel() {
        initComponents();
    }
    
    public AssignTechnicianJPanel(JPanel workAreaContainer, UserAccounts userAccount, PestControlWorkRequest request, Ecosystem ecosystem) {
        initComponents();
        this.workAreaContainer = workAreaContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        this.request = request;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        technicianTable = new javax.swing.JTable();
        assignButton = new javax.swing.JButton();
        pic = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("                        Assign Technician's");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 0, 660, 47));

        backButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        technicianTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Technician Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(technicianTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 108, 327, 187));

        assignButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        assignButton.setText("Assign Request To Selected Technician");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });
        add(assignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 334, 336, -1));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/PestControlAdmin/org1.jpeg"))); // NOI18N
        add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 89, 212, 274));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = technicianTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to view details","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {

            PestControlTechnician technician  = (PestControlTechnician)technicianTable.getValueAt(selectedRow, 0);
            technician.getTechnicianRequestList().add(request);
            technician.setAvailability(false);
            request.setStatus("Assigned Technician");

            for(Customer customer:ecosystem.getCustomerDirectory().getCustomerList()){
                if(request.getCustName().equals(customer.getUsername())){
                    for(PestControlWorkRequest request : customer.getPestControlWorkRequestList()){
                        if(request.getStatus().equals("In Progress")){
                            request.setStatus("Assigned Technician");
                        }
                    }
                }
            }
            workAreaContainer.remove(this);
            CardLayout layout = (CardLayout) workAreaContainer.getLayout();
            layout.previous(workAreaContainer);

        }
    }//GEN-LAST:event_assignButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pic;
    private javax.swing.JTable technicianTable;
    // End of variables declaration//GEN-END:variables
}
