/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SysAdmin;

import Business.Ecosystem;
import UserAccounts.UserAccounts;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hi
 */
public class SalonOrganisationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalonOrganisationJPanel
     */
    private JPanel workAreaContainer;
    private Ecosystem system;
    UserAccounts userAccounts;
    
    public SalonOrganisationJPanel() {
        initComponents();
    }
    
    public SalonOrganisationJPanel(JPanel workAreaContainer, Ecosystem system) {
        initComponents();
        this.workAreaContainer = workAreaContainer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        selectPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        salonAdminBtn = new javax.swing.JButton();
        beauticianBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        createPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        selectPanel.setBackground(new java.awt.Color(255, 255, 255));
        selectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("SALON ORGANISATION");
        selectPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        salonAdminBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        salonAdminBtn.setText("Create Salon Admin");
        salonAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salonAdminBtnActionPerformed(evt);
            }
        });
        selectPanel.add(salonAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        beauticianBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        beauticianBtn.setText("Create Beautician");
        beauticianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beauticianBtnActionPerformed(evt);
            }
        });
        selectPanel.add(beauticianBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        selectPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jSplitPane1.setTopComponent(selectPanel);

        createPanel.setBackground(new java.awt.Color(255, 255, 255));
        createPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/SysAdmin/360_F_291376220_4vAflyBidF8fl0JesmL26rTExhZHd72Y.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        createPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 646, 485));

        jSplitPane1.setRightComponent(createPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void salonAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salonAdminBtnActionPerformed
        // TODO add your handling code here:
        CreateSalonAdminJPanel salonAdminJPanel=new CreateSalonAdminJPanel(createPanel, system);
        createPanel.add("Create Salon Admin",salonAdminJPanel);
        CardLayout lay = (CardLayout)createPanel.getLayout();
        lay.next(createPanel);
    }//GEN-LAST:event_salonAdminBtnActionPerformed

    private void beauticianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beauticianBtnActionPerformed
        // TODO add your handling code here:
        CreateBeauticianJPanel beauticianJPanel=new CreateBeauticianJPanel(createPanel, system);
        createPanel.add("Create Beautician",beauticianJPanel);
        CardLayout lay = (CardLayout)createPanel.getLayout();
        lay.next(createPanel);
    }//GEN-LAST:event_beauticianBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        Component[] componentArray = workAreaContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdmin = (SystemAdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beauticianBtn;
    private javax.swing.JPanel createPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton salonAdminBtn;
    private javax.swing.JPanel selectPanel;
    // End of variables declaration//GEN-END:variables
}
