/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SysAdmin;

import Business.Ecosystem;
import UserAccounts.UserAccounts;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author hi
 */


public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    
    private JPanel workAreaContainer;
    private Ecosystem ecosystem;
    private UserAccounts userAccount;
    
    
    public SystemAdminWorkAreaJPanel() {
        initComponents();
    }

    public SystemAdminWorkAreaJPanel(JPanel workAreaContainer, UserAccounts userAccount, Ecosystem ecosystem) {
        initComponents();
        
        this.workAreaContainer = workAreaContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        salonBtn = new javax.swing.JButton();
        homeServicesBtn = new javax.swing.JButton();
        pestControlBtn = new javax.swing.JButton();
        paintingBtn = new javax.swing.JButton();
        storeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setText("System Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        salonBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        salonBtn.setText("Salon Services");
        salonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salonBtnActionPerformed(evt);
            }
        });
        add(salonBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 120, -1));

        homeServicesBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        homeServicesBtn.setText("Home Repair Services");
        homeServicesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeServicesBtnActionPerformed(evt);
            }
        });
        add(homeServicesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        pestControlBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pestControlBtn.setText("Pest Control Services");
        pestControlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pestControlBtnActionPerformed(evt);
            }
        });
        add(pestControlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, -1, -1));

        paintingBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        paintingBtn.setText("Painting Services");
        paintingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintingBtnActionPerformed(evt);
            }
        });
        add(paintingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        storeBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        storeBtn.setText("Shopping Services");
        storeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeBtnActionPerformed(evt);
            }
        });
        add(storeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 180, -1));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel2.setText("Enterprises");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 150, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/SysAdmin/enterprises.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 846, -1));

        customerBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        customerBtn.setText("Customer");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });
        add(customerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void salonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salonBtnActionPerformed
        // TODO add your handling code here:
        SalonOrganisationJPanel salonOrgJPanel=new SalonOrganisationJPanel(workAreaContainer, ecosystem);
        workAreaContainer.add("Open Salon Organisation",salonOrgJPanel);
        CardLayout lay = (CardLayout)workAreaContainer.getLayout();
        lay.next(workAreaContainer);
    }//GEN-LAST:event_salonBtnActionPerformed

    private void homeServicesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeServicesBtnActionPerformed
        // TODO add your handling code here:
        HomeServicesOrganisationJPanel servicesOrgJPanel=new HomeServicesOrganisationJPanel(workAreaContainer, ecosystem);
        workAreaContainer.add("Open Salon Organisation",servicesOrgJPanel);
        CardLayout lay = (CardLayout)workAreaContainer.getLayout();
        lay.next(workAreaContainer);
    }//GEN-LAST:event_homeServicesBtnActionPerformed

    private void pestControlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pestControlBtnActionPerformed
        // TODO add your handling code here:
        PestControlOrganisationJPanel pestOrgJPanel=new PestControlOrganisationJPanel(workAreaContainer, ecosystem);
        workAreaContainer.add("Open Salon Organisation",pestOrgJPanel);
        CardLayout lay = (CardLayout)workAreaContainer.getLayout();
        lay.next(workAreaContainer);
    }//GEN-LAST:event_pestControlBtnActionPerformed

    private void paintingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintingBtnActionPerformed
        // TODO add your handling code here:
        PaintingOrganisationJPanel paintOrgJPanel=new PaintingOrganisationJPanel(workAreaContainer, ecosystem);
        workAreaContainer.add("Open Painting Organisation",paintOrgJPanel);
        CardLayout lay = (CardLayout)workAreaContainer.getLayout();
        lay.next(workAreaContainer);
    }//GEN-LAST:event_paintingBtnActionPerformed

    private void storeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeBtnActionPerformed
        // TODO add your handling code here:
        CreateStoreAdminJPanel storeAdminJPanel=new CreateStoreAdminJPanel(workAreaContainer, ecosystem);
        workAreaContainer.add("Create Store Admin",storeAdminJPanel);
        CardLayout lay = (CardLayout)workAreaContainer.getLayout();
        lay.next(workAreaContainer);
    }//GEN-LAST:event_storeBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        CreateCustomerJPanel customerJPanel=new CreateCustomerJPanel(workAreaContainer, ecosystem);
        workAreaContainer.add("Create Customer",customerJPanel);
        CardLayout lay = (CardLayout)workAreaContainer.getLayout();
        lay.next(workAreaContainer);
    }//GEN-LAST:event_customerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton homeServicesBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton paintingBtn;
    private javax.swing.JButton pestControlBtn;
    private javax.swing.JButton salonBtn;
    private javax.swing.JButton storeBtn;
    // End of variables declaration//GEN-END:variables
}
