/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HomeServiceAdmin;

import Business.Ecosystem;
import HomePainting.HomePainting;
import HomeService.HomeService;
import HomeService.Service;
import UserAccounts.UserAccounts;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanujkodali
 */
public class ManageHomeWorkerServicesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageHomeWorkerServicesJPanel
     */
    private JPanel workAreaContainer;
    private Ecosystem ecosystem;
    private UserAccounts userAccount;
    
  


    public ManageHomeWorkerServicesJPanel() {
        initComponents();
    }
  
      public  ManageHomeWorkerServicesJPanel(JPanel workAreaContainer, UserAccounts userAccount, Ecosystem ecosystem) {
        initComponents();
        
        this.workAreaContainer = workAreaContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        servTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldServiceName = new javax.swing.JTextField();
        fieldDesc = new javax.swing.JTextField();
        fieldType = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Manage HomeWorker Services");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 6, -1, -1));

        servTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service Name", "Description", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(servTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 59, -1, 199));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Service Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 325, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Description:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 379, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Type:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 432, -1, -1));
        add(fieldServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 103, -1));
        add(fieldDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 374, 103, -1));
        add(fieldType, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 427, 103, -1));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setText("Add Services");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 471, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/HomeServiceAdmin/service23.jpeg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, 189, 250));

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) servTable.getModel();
        model.setRowCount(0);

        for (HomeService hs:ecosystem.getHomeServiceDirectory().getHomeServiceList()) {
            if(hs.getUserName().equals(userAccount.getUsername())){
               for(Service serv: hs.getServiceList()){
                Object[] row = new Object[3];
                row[0] = serv.getServiceName();
                row[1] = serv.getServiceDescription();
                row[2] = serv.getServiceType();
                model.addRow(row);
               } 
            } 
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = fieldServiceName.getText();
        String desc = fieldDesc.getText();
        String type = fieldType.getText();

        try {
            if(name == null || name.isEmpty()){
                throw new NullPointerException("Service Name field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Service Name field cannot be Empty !!!");
            return;
        }

        try {
            if(desc==null || desc.isEmpty()){
                throw new NullPointerException("Description field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Description field cannot be Empty !!!");
            return;
        }

        try {
            if(type==null || type.isEmpty()){
                throw new NullPointerException("Type Field cannot be empty !!!");
            }
        }  catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Type Field cannot be empty !!!");
            return;
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Type !!!");
            return;
        }

        for(HomeService hs:ecosystem.getHomeServiceDirectory().getHomeServiceList()){
            if(hs.getUserName().equals(userAccount.getUsername())){
                ecosystem.getHomeServiceDirectory().addServiceTypes(hs, name, desc, type);
            }
        }

        fieldServiceName.setText("");
        fieldDesc.setText("");
        fieldType.setText("");
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldDesc;
    private javax.swing.JTextField fieldServiceName;
    private javax.swing.JTextField fieldType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable servTable;
    // End of variables declaration//GEN-END:variables
}
