/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HomeServiceAdmin;

import Business.Ecosystem;
import HomeService.HomeService;
import SalonServices.Salon;
import UserAccounts.UserAccounts;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tanujkodali
 */
public class ManageHomeWorkerInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageHomeWorkerInfoJPanel
     */
    
     private JPanel workAreaContainer;
    private Ecosystem ecosystem;
    private UserAccounts userAccount;
   
    public ManageHomeWorkerInfoJPanel() {
        initComponents();
    }
     public ManageHomeWorkerInfoJPanel(JPanel workAreaContainer, UserAccounts userAccount, Ecosystem ecosystem) {
        initComponents();
        
        this.workAreaContainer = workAreaContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        
        entName.setEnabled(false);
        entAddress.setEnabled(false);
        entContact.setEnabled(false);
        entEmail.setEnabled(false);
        saveBtn.setEnabled(false);
        updateBtn.setEnabled(true);
        
        
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        entName = new javax.swing.JTextField();
        entAddress = new javax.swing.JTextField();
        entContact = new javax.swing.JTextField();
        entEmail = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Manage HomeWorker Organisation Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/HomeServiceAdmin/worker3.jpeg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 323, 341));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("HomeWorker Enterprize Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 165, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("HomeWorker Enterprize Address:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 223, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("HomeWorker PhoneNumber:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 282, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Email:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 339, -1, -1));
        add(entName, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 166, 167, -1));
        add(entAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 224, 163, -1));
        add(entContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 283, 163, -1));
        add(entEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 340, 163, -1));

        updateBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 437, -1, -1));

        saveBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 437, -1, -1));

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 546, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        entName.setEnabled(true);
        entAddress.setEnabled(true);
        entContact.setEnabled(true);
        entEmail.setEnabled(true);
        saveBtn.setEnabled(true);
        updateBtn.setEnabled(false);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String name = entName.getText();
        String address = entAddress.getText();
        String number = entContact.getText();
       String email = entEmail.getText();
        
        try {
             if(name==null || name.isEmpty()){
                throw new NullPointerException("Please Enter All Fields");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please Enter All Fields");        
            return;   
        }
        
        try {
             if(address==null || address.isEmpty()){
                throw new NullPointerException("Please Enter All Fields");    
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please Enter All Fields");          
            return;   
        }
        
         try {
             
            if(number==null || number.isEmpty()){
                throw new NullPointerException("Phone Number Field cannot be Empty !!!");
            }else if(Pattern.matches("^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$", number) == false){
                throw new Exception("Enter a Valid Phone number !!!");
            }     
        }  catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Phone Number Field cannot be Empty !!!");
            return;
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter a Valid Phone number !!!");
            return;
        }
         
        try {
             if(email==null || email.isEmpty()){
                throw new NullPointerException("Email Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Email Field cannot be Empty !!!");        
            return;   
        }
        
        for(HomeService hs:ecosystem.getHomeServiceDirectory().getHomeServiceList()){
           if(hs.getUserName().equals(userAccount.getUsername())){
                ecosystem.getHomeServiceDirectory().updateHomeServiceOrgInfo(hs, name, number, address, email);
            }
        }
        
        entName.setEnabled(false);
        entAddress.setEnabled(false);
        entContact.setEnabled(false);
        entEmail.setEnabled(false);
        saveBtn.setEnabled(false);
        updateBtn.setEnabled(true);
                                
    }//GEN-LAST:event_saveBtnActionPerformed

    private void populateFields() {
        for(HomeService hserivce:ecosystem.getHomeServiceDirectory().getHomeServiceList()){
           if(hserivce.getUserName().equals(userAccount.getUsername())){
                entName.setText(hserivce.getHomeServiceName());
                entAddress.setText(hserivce.getHomeServiceAddress());
                entContact.setText(hserivce.getHomeServicePhNum());
                entEmail.setText(hserivce.getHomeServiceEmail());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entAddress;
    private javax.swing.JTextField entContact;
    private javax.swing.JTextField entEmail;
    private javax.swing.JTextField entName;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
