/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PaitingAdmin;

/**
 *
 * @author 91730
 */
public class ManagePaintingInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePaintingInformationJPanel
     */
    public ManagePaintingInformationJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateInfoBtn = new javax.swing.JButton();
        saveInfoBtn = new javax.swing.JButton();
        paintingContactField = new javax.swing.JTextField();
        paintingAddressField = new javax.swing.JTextField();
        paintingNameField = new javax.swing.JTextField();
        paitingOrgContactLabel = new javax.swing.JLabel();
        paitingOrgAddressLabel = new javax.swing.JLabel();
        paitingOrgNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        organizationTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateInfoBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        updateInfoBtn.setText("Update Info");
        updateInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoBtnActionPerformed(evt);
            }
        });
        add(updateInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 111, -1));

        saveInfoBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        saveInfoBtn.setText("Save Info");
        saveInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveInfoBtnActionPerformed(evt);
            }
        });
        add(saveInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 102, -1));

        paintingContactField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        paintingContactField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paintingContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintingContactFieldActionPerformed(evt);
            }
        });
        add(paintingContactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 230, 30));

        paintingAddressField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        paintingAddressField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(paintingAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 230, 30));

        paintingNameField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        paintingNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(paintingNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 230, 30));

        paitingOrgContactLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        paitingOrgContactLabel.setText("Painting Organization Contact");
        add(paitingOrgContactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        paitingOrgAddressLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        paitingOrgAddressLabel.setText("Painting Organization Address");
        add(paitingOrgAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, 20));

        paitingOrgNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        paitingOrgNameLabel.setText("Painting Organization Name");
        add(paitingOrgNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, -110, 684, 776));

        organizationTitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        organizationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        organizationTitle.setText("Manage Paiting Organization Information");
        add(organizationTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 422, 29));

        btnBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/PaitingAdmin/painter3.jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 6, 300, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void updateInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoBtnActionPerformed
        // TODO add your handling code here:
        paintingNameField.setEnabled(true);
        paintingAddressField.setEnabled(true);
        paintingContactField.setEnabled(true);
        saveInfoBtn.setEnabled(true);
        updateInfoBtn.setEnabled(false);
    }//GEN-LAST:event_updateInfoBtnActionPerformed

    private void saveInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveInfoBtnActionPerformed
//        // TODO add your handling code here:
//        String name = paintingNameField.getText();
//        String address = paintingAddressField.getText();
//        String number = paintingContactField.getText();
//
//        try {
//            if(name==null || name.isEmpty()){
//                throw new NullPointerException("SnowClearingOrg Name Field cannot be Empty !!!");
//
//            }
//        } catch(NullPointerException e){
//            JOptionPane.showMessageDialog(null, "SnowClearing Organizations Name Field cannot be Empty !!!");
//            return;
//        }
//
//        try {
//            if(address==null || address.isEmpty()){
//                throw new NullPointerException("SnowClearing Organization Field cannot be Empty !!!");
//            }
//        } catch(NullPointerException e){
//            JOptionPane.showMessageDialog(null, "SnowClearing Organization Field cannot be Empty !!!");
//            return;
//        }
//
//        try {
//
//            if(number==null || number.isEmpty()){
//                throw new NullPointerException("SnowClearingOrg Phone Number Field cannot be Empty !!!");
//            }else if(Pattern.matches("^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$", number) == false){
//                throw new Exception("Enter a Valid Phone number !!!");
//            }
//        }  catch(NullPointerException e){
//            JOptionPane.showMessageDialog(null, "SnowClearingOrg Phone Number Field cannot be Empty !!!");
//            return;
//        }catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Enter a Valid Phone number !!!");
//            return;
//        }
//
//        for(SoupKitchenOrg org:system.getSoupKitchenOrgDirectory().getSoupKitchenList()){
//            if(org.getUserName().equals(account.getUsername())){
//                system.getSoupKitchenOrgDirectory().updateSoupInfo(org, name, number, address);
//            }
//        }
//
//        paintingNameField.setEnabled(false);
//        paintingAddressField.setEnabled(false);
//        paintingContactField.setEnabled(false);
//        saveInfoBtn.setEnabled(false);
//        updateInfoBtn.setEnabled(true);
    }//GEN-LAST:event_saveInfoBtnActionPerformed

    private void paintingContactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintingContactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintingContactFieldActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
//        userProcessContainer.remove(this);
//
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel organizationTitle;
    private javax.swing.JTextField paintingAddressField;
    private javax.swing.JTextField paintingContactField;
    private javax.swing.JTextField paintingNameField;
    private javax.swing.JLabel paitingOrgAddressLabel;
    private javax.swing.JLabel paitingOrgContactLabel;
    private javax.swing.JLabel paitingOrgNameLabel;
    private javax.swing.JButton saveInfoBtn;
    private javax.swing.JButton updateInfoBtn;
    // End of variables declaration//GEN-END:variables
}
