/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PaitingAdmin;

import Business.Ecosystem;
import HomePainting.HomePainting;
import HomePainting.PaintingPackages;
import UserAccounts.UserAccounts;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class ManagePaintingServicesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePaintingServicesJPanel
     */
    
    private JPanel workAreaContainer;
    private Ecosystem ecosystem;
    private UserAccounts userAccount;
    
    
    public ManagePaintingServicesJPanel(JPanel workAreaContainer, UserAccounts userAccount, Ecosystem ecosystem) {
        initComponents();
        
        this.workAreaContainer = workAreaContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        populateTable();
    }
    
    public ManagePaintingServicesJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialType = new javax.swing.JLabel();
        serviceTypeField = new javax.swing.JTextField();
        servicetype = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paintTable = new javax.swing.JTable();
        materialTypeField = new javax.swing.JTextField();
        serviceDescription = new javax.swing.JLabel();
        btnAddService = new javax.swing.JButton();
        descriptionField = new javax.swing.JTextField();
        paintingServiceTitle = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        materialType.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        materialType.setText("Paint Color");
        add(materialType, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        serviceTypeField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        serviceTypeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(serviceTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 230, 30));

        servicetype.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        servicetype.setText("Painting Service Type");
        add(servicetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        paintTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Painting Service Type", "Description", "Paint Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(paintTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 607, 122));

        materialTypeField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        materialTypeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(materialTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 230, 30));

        serviceDescription.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        serviceDescription.setText("Description");
        add(serviceDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        btnAddService.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        btnAddService.setText("Add Service Type");
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });
        add(btnAddService, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 180, -1));

        descriptionField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        descriptionField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(descriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 230, 30));

        paintingServiceTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        paintingServiceTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paintingServiceTitle.setText("Manage Paiting Services Offered");
        add(paintingServiceTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 470, -1));

        backButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/PaitingAdmin/painter1.jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 270, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) paintTable.getModel();
        model.setRowCount(0);

        for (HomePainting hp:ecosystem.getHomePaintingDirectory().getHomePaintingList()) {
            if (hp.getUsername().equals(userAccount.getUsername())) {
               for(PaintingPackages paint: hp.getPaintingPackageList()){
                Object[] row = new Object[3];
                row[0] = paint.getPaintPackageType();
                row[1] = paint.getPaintDesc();
                row[2] = paint.getColor();
                model.addRow(row);
               } 
            } 
        }
    }

        
    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        // TODO add your handling code here:
        String name = serviceTypeField.getText();
        String desc = descriptionField.getText();
        String color = materialTypeField.getText();

        try {
            if(name == null || name.isEmpty()){
                throw new NullPointerException("Service Name field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Service Name field cannot be Empty !!!");
            return;
        }

        try {
            if(desc==null || desc.isEmpty()){
                throw new NullPointerException("Description field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Description field cannot be Empty !!!");
            return;
        }

        try {
            if(color==null || color.isEmpty()){
                throw new NullPointerException("Color Field cannot be empty !!!");
            }
        }  catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Color Field cannot be empty !!!");
            return;
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Color !!!");
            return;
        }

        for(HomePainting hp:ecosystem.getHomePaintingDirectory().getHomePaintingList()){
            if(hp.getUsername().equals(userAccount.getUsername())){
                ecosystem.getHomePaintingDirectory().addPaintPackage(hp, name, desc, color);
            }
        }

        serviceTypeField.setText("");
        descriptionField.setText("");
        materialTypeField.setText("");
        populateTable();
    }//GEN-LAST:event_btnAddServiceActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton btnAddService;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel materialType;
    private javax.swing.JTextField materialTypeField;
    private javax.swing.JTable paintTable;
    private javax.swing.JLabel paintingServiceTitle;
    private javax.swing.JLabel serviceDescription;
    private javax.swing.JTextField serviceTypeField;
    private javax.swing.JLabel servicetype;
    // End of variables declaration//GEN-END:variables
}
