/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HomeServiceTechnicianPanels;

import Business.Ecosystem;
import UI.BeauticianPanels.BeauticianWorkAreaJPanel;
import UserAccounts.UserAccounts;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author 91730
 */
public class HomeServiceTechnicianHomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomeServiceTechnicianJPanel
     */
    private JPanel workAreaContainer;
    private Ecosystem ecosystem;
    private UserAccounts userAccount;
    
    public HomeServiceTechnicianHomeJPanel() {
        initComponents();
    }

    public HomeServiceTechnicianHomeJPanel(JPanel workAreaContainer, UserAccounts userAccounts, Ecosystem ecosystem) {
        initComponents();
        
        this.workAreaContainer = workAreaContainer;
        this.userAccount = userAccounts;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        home = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Home Service's");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/HomeServiceTechnicianPanels/homeservices.jpeg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 90, 290, 279));

        home.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        home.setText("Home Services");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 375, 197, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        HomeServiceTechnicianWorkAreaJPanel wr = new HomeServiceTechnicianWorkAreaJPanel(workAreaContainer, userAccount, ecosystem);
        workAreaContainer.add("Manage Requests", wr);
        CardLayout layout = (CardLayout)workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_homeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
