/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PestControlTechnician;

import Business.Ecosystem;
import PestControlTechnician.PestControlTechnician;
import UserAccounts.UserAccounts;
import WorkQueue.PestControlWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class TechnicianAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TechnicianAreaJPanel
     */
    private JPanel workAreaContainer;
    private Ecosystem ecosystem;
    private UserAccounts userAccount;

    public TechnicianAreaJPanel() {
        initComponents();
    }
   
    public TechnicianAreaJPanel(JPanel workAreaContainer, UserAccounts userAccount,Ecosystem ecosystem) {
        initComponents();
        
        this.workAreaContainer = workAreaContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequestDetails = new javax.swing.JTable();
        inProgress = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/PestControlTechnician/PestControlTechnician.jpeg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 567));

        tblRequestDetails.setBackground(new java.awt.Color(133, 211, 255));
        tblRequestDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Pest Control Org Name", "Member Name", "Pickup Address", "Status", "Problem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequestDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 894, 200));

        inProgress.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        inProgress.setText("In Progress");
        inProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inProgressActionPerformed(evt);
            }
        });
        add(inProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, 200, -1));

        jLabel1.setFont(new java.awt.Font("Al Nile", 1, 24)); // NOI18N
        jLabel1.setText("Technician Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void inProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inProgressActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequestDetails.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!!");
            return;
        }
        PestControlWorkRequest pestControl = (PestControlWorkRequest)tblRequestDetails.getValueAt(selectedRow, 0);

        if(pestControl.getStatus().equals("Completed")){
            JOptionPane.showMessageDialog(null,"Already Completed", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(pestControl.getStatus().equals("New Order") || pestControl.getStatus().equals("In Progress")){
            JOptionPane.showMessageDialog(null,"Request is not yet Assigned", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            TechnicianRequestJPanel processOrderJPanel = new TechnicianRequestJPanel(workAreaContainer, pestControl,ecosystem, userAccount);
            workAreaContainer.add("processWorkRequestJPanel", processOrderJPanel);
            CardLayout layout = (CardLayout) workAreaContainer.getLayout();
            layout.next(workAreaContainer);
        }
    }//GEN-LAST:event_inProgressActionPerformed

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblRequestDetails.getModel();
        model.setRowCount(0);
        
        for(PestControlTechnician technician : ecosystem.getPestControlTechnicianDirectory().getPestControlTechnicianList()){
            try{
            if(technician.getTechnicianUsername().equals(userAccount.getUsername())){
                
                for(PestControlWorkRequest request : technician.getTechnicianRequestList()){
                Object[] row = new Object[6];
                
                row[0] = request;
                row[1] = request.getPestControlCOmpanyName();
                row[2] = request.getCustName();
                row[3] = request.getServiceAddress();
                row[4] = request.getStatus();
                row[5] = request.getIssue();
                model.addRow(row);     
                }
            }}catch(NullPointerException e){
            System.out.println("No request has been placed yet !!!");
            return;
        }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inProgress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequestDetails;
    // End of variables declaration//GEN-END:variables
}
